language: csharp
solution: SaveTheWorld.sln
 
install:
  - nuget restore SaveTheWorld.sln
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
  
script:
  - msbuild SaveTheWorld.sln
  - ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./SaveTheWorld.Tests/bin/Debug/SaveTheWorld.Tests.dll
  