language: csharp
solution: SaveTheWorld.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore SaveTheWorld.sln -OutputDirectory testrunner
  
script:
  - xbuild ./src/yoursolution.sln
  - ./testrunner/nunit-console ./SaveTheWorld.Tests/bin/Release/SaveTheWorld.Tests.dll