language: csharp
mono: none
dotnet: 1.0.1
dist: trusty
script:
 - dotnet restore
 
install:
  - nuget restore SaveTheWorld.sln
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
  
script:
  - msbuild SaveTheWorld.sln
  - ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console ./SaveTheWorld.Tests/bin/Debug/netcoreapp1.1/SaveTheWorld.Tests.dll